
KEYWORDS = {
    "fi":       "if",
    "esle":     "else",
    "file":     "elif",
    "rof":      "for",
    "elihw":    "while",
    "nruter":   "return",
    "fed":      "def",
    "ssalc":    "class",
    "tropmi":   "import",
    "morf":     "from",
    "sa":       "as",
    "ni":       "in",
    "ton":      "not",
    "dna":      "and",
    "ro":       "or",
    "si":       "is",
    "eurT":     "True",
    "eslaF":    "False",
    "enoN":     "None",
    "ssap":     "pass",
    "kaerb":    "break",
    "eunitnoc": "continue",
    "yrt":      "try",
    "tpecxe":   "except",
    "yllanif":  "finally",
    "esiar":    "raise",
    "htiw":     "with",
    "adbmal":   "lambda",
    "dleiY":    "yield",
    "labolg":   "global",
    "led":      "del",
}

BUILTINS = {
    "tnirp":  "print",
    "tupni":  "input",
    "tni":    "int",
    "taolf":  "float",
    "rts":    "str",
    "loob":   "bool",
    "nel":    "len",
    "egnar":  "range",
    "tsil":   "list",
    "epyt":   "type",
}
